[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "println"          
path = "src/println.rs"

[[bin]]
name = "flowcontrol"          
path = "src/flowcontrol.rs"

[dependencies]


